name: Daily Menu to Google Chat

on:
  schedule:
    - cron: "30 1 * * 1-5"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  URL: ${{ secrets.MENU_SOURCE_URL }}
  WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv

      - name: Fetch image and prepare site files
        run: |
          python main.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
